version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/postgres/data/
    environment:
      - POSTGRES_DB=sreality_clone_db
      - POSTGRES_USER=vikiedr
      - POSTGRES_PASSWORD=wouldnt_normally_put_password_here
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "vikiedr", "-d", "sreality_clone_db", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  web:
    build: ./web
    command: sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./web:/code
    ports:
      - "8080:8000"
    environment:
      - POSTGRES_NAME=sreality_clone_db
      - POSTGRES_USER=vikiedr
      - POSTGRES_PASSWORD=wouldnt_normally_put_password_here
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "manage.py", "check"]
      interval: 10s
      timeout: 5s
      retries: 3
  scraper:
    build: ./scraper
    command: scrapy crawl flatsSell
    volumes:
      - ./scraper:/code
    environment:
      - POSTGRES_NAME=sreality_clone_db
      - POSTGRES_USER=vikiedr
      - POSTGRES_PASSWORD=wouldnt_normally_put_password_here
    depends_on:
      web:
        condition: service_healthy
volumes:
  postgres_data: